M48
; DRILL file {KiCad 7.0.11-2.fc39} date Sun 24 Mar 2024 03:41:56 AM +08
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-24T03:41:56+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-2.fc39
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.302
%
G90
G05
T1
X135.89Y-85.09
X135.89Y-118.11
X168.91Y-85.09
X168.91Y-118.11
M30
